name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'davidgiven/cpm65'
        path: 'cpm65'

    - name: apt
      run: sudo apt update && sudo apt install cc1541 cpmtools libfmt-dev fp-compiler moreutils srecord 64tass

    - name: install llvm-mos
      run: |
        wget -O - https://github.com/llvm-mos/llvm-mos-sdk/releases/latest/download/llvm-mos-linux.tar.xz | tar xJf - -C $HOME

    - name: make
      run: make -C cpm65 LLVM=$HOME/llvm-mos/bin

    - name: date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

    - name: tag
      run: |
        cd cpm65
        git config user.name "davidgiven"
        git config user.email "dg@cowlark.com"
        git tag -f dev
        git push -f origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: delete-old-assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: dev
        assets: | 
          apple2e.po
          apple2e_b.po
          atari800.atr
          atari800b.atr
          atari800c.atr
          atari800hd.atr
          atari800xlhd.atr
          bbcmicro.ssd
          c64.d64
          kim-1-iec.zip
          kim-1-k1013.zip
          kim-1-sdcard.zip
          nano6502.img
          nano6502_sysonly.img
          neo6502.zip
          oricatmos.dsk
          osi400f.os8
          osi400mf.os5
          osi500f.os8
          osi500mf.os5
          osi600f.os8
          osi600mf.os5
          osif-b.os8
          osimf-b.os5
          osimf-c.os5
          osimf-d.os5
          osiserf.os8
          pet4032.d64
          pet8032.d64
          pet8096.d64
          snes.smc
          vic20.d64
          x16.zip
        fail-if-no-assets: false

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: Development build ${{ env.RELEASE_DATE }}
        files: |
          cpm65/apple2e.po
          cpm65/atari800.atr
          cpm65/atari800b.atr
          cpm65/atari800c.atr
          cpm65/atari800hd.atr
          cpm65/atari800xlhd.atr
          cpm65/bbcmicro.ssd
          cpm65/c64.d64
          cpm65/kim-1-iec.zip
          cpm65/kim-1-k1013.zip
          cpm65/kim-1-sdcard.zip
          cpm65/nano6502.img
          cpm65/nano6502_sysonly.img
          cpm65/neo6502.zip
          cpm65/oric.dsk
          cpm65/osi400f.os8
          cpm65/osi400mf.os5
          cpm65/osi500f.os8
          cpm65/osi500mf.os5
          cpm65/osi600f.os8
          cpm65/osi600mf.os5
          cpm65/osif-b.os8
          cpm65/osimf-b.os5
          cpm65/osimf-c.os5
          cpm65/osimf-d.os5
          cpm65/osiserf.os8
          cpm65/pet4032.d64
          cpm65/pet8032.d64
          cpm65/pet8096.d64
          cpm65/snes.smc
          cpm65/vic20.d64
          cpm65/x16.zip
        tag_name: dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

